kind: Deployment
apiVersion: apps/v1
metadata:
  name: hwameistor-alerter
  namespace: local-storage-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwameistor-alerter
  template:
    metadata:
      labels:
        app: hwameistor-alerter
    spec:
      serviceAccount: storage-admin
      priorityClassName: system-cluster-critical
      containers:
        - name: main
          #image: ghcr.io/hwameistor/localstorage-local-storage-alerter:v0.0.1
          image: ghcr.io/hwameistor/hwameistor-alerter:v0.0.1
          imagePullPolicy: Always
          args:
            - --debug=true
            - --is-virtual-machine=false
            - --namespace=$(POD_NAMESPACE)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
