apiVersion: v1
kind: Service
metadata:
  name: nginx-local-storage-lvm-svc
  labels:
    app: nginx-local-storage-lvm-sts
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx-local-storage-lvm-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-local-storage-lvm-sts
spec:
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx-local-storage-lvm-sts
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-local-storage-lvm-sts
    spec:
      schedulerName: hwameistor-scheduler
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html

  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage-hdd-lvm-sts
        resources:
          requests:
            storage: 1Gi