kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-storage-pvc-lvm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-hdd-lvm
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-storage-pvc-lvm-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-hdd-lvm
  resources:
    requests:
      storage: 1Gi
